---
- name: Create Dir
  file:
    path: "{{ dir_to_create.dir }}"
    state: directory
    mode: "{{ dir_to_create.mode }}" 
- name: Download file
  get_url:
    url: "{{ file_to_download.url }}"
    dest: "{{ dir_to_create.dir }}/git_help.pdf"
    mode: "{{ file_to_download.mode }}"
