---
- name: Pull image {{ image_name }}
  docker_image:
    name: "{{ image_name }}"
    source: pull
- name: Deploy {{container_name }} in docker
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: present
